/*Copyright (c) 2023-2024 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.e_commerce_web_app.shopingapp.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Lazy;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.annotations.EntityService;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.e_commerce_web_app.shopingapp.Cart;
import com.e_commerce_web_app.shopingapp.Orderlist;
import com.e_commerce_web_app.shopingapp.UserAddress;
import com.e_commerce_web_app.shopingapp.Userinfo;


/**
 * ServiceImpl object for domain model class Userinfo.
 *
 * @see Userinfo
 */
@Service("shopingapp.UserinfoService")
@Validated
@EntityService(entityClass = Userinfo.class, serviceId = "shopingapp")
public class UserinfoServiceImpl implements UserinfoService {

    private static final Logger LOGGER = LoggerFactory.getLogger(UserinfoServiceImpl.class);

    @Lazy
    @Autowired
    @Qualifier("shopingapp.CartService")
    private CartService cartService;

    @Lazy
    @Autowired
    @Qualifier("shopingapp.OrderlistService")
    private OrderlistService orderlistService;

    @Lazy
    @Autowired
    @Qualifier("shopingapp.UserAddressService")
    private UserAddressService userAddressService;

    @Autowired
    @Qualifier("shopingapp.UserinfoDao")
    private WMGenericDao<Userinfo, Integer> wmGenericDao;

    @Autowired
    @Qualifier("wmAppObjectMapper")
    private ObjectMapper objectMapper;


    public void setWMGenericDao(WMGenericDao<Userinfo, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "shopingappTransactionManager")
    @Override
    public Userinfo create(Userinfo userinfo) {
        LOGGER.debug("Creating a new Userinfo with information: {}", userinfo);

        Userinfo userinfoCreated = this.wmGenericDao.create(userinfo);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(userinfoCreated);
    }

    @Transactional(readOnly = true, value = "shopingappTransactionManager")
    @Override
    public Userinfo getById(Integer userinfoId) {
        LOGGER.debug("Finding Userinfo by id: {}", userinfoId);
        return this.wmGenericDao.findById(userinfoId);
    }

    @Transactional(readOnly = true, value = "shopingappTransactionManager")
    @Override
    public Userinfo findById(Integer userinfoId) {
        LOGGER.debug("Finding Userinfo by id: {}", userinfoId);
        try {
            return this.wmGenericDao.findById(userinfoId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No Userinfo found with id: {}", userinfoId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "shopingappTransactionManager")
    @Override
    public List<Userinfo> findByMultipleIds(List<Integer> userinfoIds, boolean orderedReturn) {
        LOGGER.debug("Finding Userinfos by ids: {}", userinfoIds);

        return this.wmGenericDao.findByMultipleIds(userinfoIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "shopingappTransactionManager")
    @Override
    public Userinfo update(Userinfo userinfo) {
        LOGGER.debug("Updating Userinfo with information: {}", userinfo);

        this.wmGenericDao.update(userinfo);
        this.wmGenericDao.refresh(userinfo);

        return userinfo;
    }

    @Transactional(value = "shopingappTransactionManager")
    @Override
    public Userinfo partialUpdate(Integer userinfoId, Map<String, Object>userinfoPatch) {
        LOGGER.debug("Partially Updating the Userinfo with id: {}", userinfoId);

        Userinfo userinfo = getById(userinfoId);

        try {
            ObjectReader userinfoReader = this.objectMapper.reader().forType(Userinfo.class).withValueToUpdate(userinfo);
            userinfo = userinfoReader.readValue(this.objectMapper.writeValueAsString(userinfoPatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", userinfoPatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        userinfo = update(userinfo);

        return userinfo;
    }

    @Transactional(value = "shopingappTransactionManager")
    @Override
    public Userinfo delete(Integer userinfoId) {
        LOGGER.debug("Deleting Userinfo with id: {}", userinfoId);
        Userinfo deleted = this.wmGenericDao.findById(userinfoId);
        if (deleted == null) {
            LOGGER.debug("No Userinfo found with id: {}", userinfoId);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), Userinfo.class.getSimpleName(), userinfoId);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "shopingappTransactionManager")
    @Override
    public void delete(Userinfo userinfo) {
        LOGGER.debug("Deleting Userinfo with {}", userinfo);
        this.wmGenericDao.delete(userinfo);
    }

    @Transactional(readOnly = true, value = "shopingappTransactionManager")
    @Override
    public Page<Userinfo> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all Userinfos");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "shopingappTransactionManager")
    @Override
    public Page<Userinfo> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all Userinfos");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "shopingappTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service shopingapp for table Userinfo to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "shopingappTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service shopingapp for table Userinfo to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "shopingappTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "shopingappTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "shopingappTransactionManager")
    @Override
    public Page<Cart> findAssociatedCarts(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated carts");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("userinfo.id = '" + id + "'");

        return cartService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "shopingappTransactionManager")
    @Override
    public Page<Orderlist> findAssociatedOrderlists(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated orderlists");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("userinfo.id = '" + id + "'");

        return orderlistService.findAll(queryBuilder.toString(), pageable);
    }

    @Transactional(readOnly = true, value = "shopingappTransactionManager")
    @Override
    public Page<UserAddress> findAssociatedUserAddresses(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated userAddresses");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("userinfo.id = '" + id + "'");

        return userAddressService.findAll(queryBuilder.toString(), pageable);
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service CartService instance
     */
    protected void setCartService(CartService service) {
        this.cartService = service;
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service OrderlistService instance
     */
    protected void setOrderlistService(OrderlistService service) {
        this.orderlistService = service;
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service UserAddressService instance
     */
    protected void setUserAddressService(UserAddressService service) {
        this.userAddressService = service;
    }

}