/*Copyright (c) 2023-2024 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.e_commerce_web_app.invoicegenerationservices.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.e_commerce_web_app.invoicegenerationservices.InvoiceGenerationServices;
import com.wordnik.swagger.annotations.Api;

/**
 * Controller object for domain model class {@link InvoiceGenerationServices}.
 * @see InvoiceGenerationServices
 */
@RestController
@Api(value = "InvoiceGenerationServicesController", description = "controller class for java service execution")
@RequestMapping("/invoiceGenerationServices")
public class InvoiceGenerationServicesController {

}