/*Copyright (c) 2023-2024 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.e_commerce_web_app.shopingapp.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import javax.validation.constraints.NotNull;

import com.fasterxml.jackson.annotation.JsonProperty;

public class AddToCartRequest implements Serializable {


    @JsonProperty("id")
    private String id;

    @JsonProperty("cartid")
    @NotNull
    private String cartid;

    @JsonProperty("productId")
    @NotNull
    private String productId;

    @JsonProperty("quantity")
    @NotNull
    private String quantity;

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getCartid() {
        return this.cartid;
    }

    public void setCartid(String cartid) {
        this.cartid = cartid;
    }

    public String getProductId() {
        return this.productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public String getQuantity() {
        return this.quantity;
    }

    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof AddToCartRequest)) return false;
        final AddToCartRequest addToCartRequest = (AddToCartRequest) o;
        return Objects.equals(getId(), addToCartRequest.getId()) &&
                Objects.equals(getCartid(), addToCartRequest.getCartid()) &&
                Objects.equals(getProductId(), addToCartRequest.getProductId()) &&
                Objects.equals(getQuantity(), addToCartRequest.getQuantity());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId(),
                getCartid(),
                getProductId(),
                getQuantity());
    }
}