/*Copyright (c) 2023-2024 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.e_commerce_web_app.shopingapp.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class CartItemCountResponse implements Serializable {


    @ColumnAlias("count(PRODUCT_ID)")
    private Long count_productId_;

    public Long getCount_productId_() {
        return this.count_productId_;
    }

    public void setCount_productId_(Long count_productId_) {
        this.count_productId_ = count_productId_;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CartItemCountResponse)) return false;
        final CartItemCountResponse cartItemCountResponse = (CartItemCountResponse) o;
        return Objects.equals(getCount_productId_(), cartItemCountResponse.getCount_productId_());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCount_productId_());
    }
}