/*Copyright (c) 2023-2024 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.e_commerce_web_app.shopingapp.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonProperty;

public class UpdateOrderRequest implements Serializable {


    @JsonProperty("order_status")
    private String orderStatus;

    @JsonProperty("orderid")
    private String orderid;

    @JsonProperty("userid")
    private String userid;

    public String getOrderStatus() {
        return this.orderStatus;
    }

    public void setOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
    }

    public String getOrderid() {
        return this.orderid;
    }

    public void setOrderid(String orderid) {
        this.orderid = orderid;
    }

    public String getUserid() {
        return this.userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof UpdateOrderRequest)) return false;
        final UpdateOrderRequest updateOrderRequest = (UpdateOrderRequest) o;
        return Objects.equals(getOrderStatus(), updateOrderRequest.getOrderStatus()) &&
                Objects.equals(getOrderid(), updateOrderRequest.getOrderid()) &&
                Objects.equals(getUserid(), updateOrderRequest.getUserid());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getOrderStatus(),
                getOrderid(),
                getUserid());
    }
}