/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.e_commerce_web_app.opencagedata.model;

import java.util.Objects;
import java.util.Arrays;
import com.e_commerce_web_app.opencagedata.model.ResponseNortheast;
import com.e_commerce_web_app.opencagedata.model.ResponseSouthwest;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseBounds
 */

public class ResponseBounds {
  @JsonProperty("southwest")
  private ResponseSouthwest southwest = null;

  @JsonProperty("northeast")
  private ResponseNortheast northeast = null;

  public ResponseBounds southwest(ResponseSouthwest southwest) {
    this.southwest = southwest;
    return this;
  }

   /**
   * Get southwest
   * @return southwest
  **/
  public ResponseSouthwest getSouthwest() {
    return southwest;
  }

  public void setSouthwest(ResponseSouthwest southwest) {
    this.southwest = southwest;
  }

  public ResponseBounds northeast(ResponseNortheast northeast) {
    this.northeast = northeast;
    return this;
  }

   /**
   * Get northeast
   * @return northeast
  **/
  public ResponseNortheast getNortheast() {
    return northeast;
  }

  public void setNortheast(ResponseNortheast northeast) {
    this.northeast = northeast;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseBounds Response_bounds = (ResponseBounds) o;
    return Objects.equals(this.southwest, Response_bounds.southwest) &&
        Objects.equals(this.northeast, Response_bounds.northeast);
  }

  @Override
  public int hashCode() {
    return Objects.hash(southwest, northeast);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseBounds {\n");
    
    sb.append("    southwest: ").append(toIndentedString(southwest)).append("\n");
    sb.append("    northeast: ").append(toIndentedString(northeast)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
