/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.e_commerce_web_app.opencagedata.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseRegions
 */

public class ResponseRegions {
  @JsonProperty("ASIA")
  private String ASIA = null;

  @JsonProperty("SG")
  private String SG = null;

  @JsonProperty("IN")
  private String IN = null;

  @JsonProperty("SOUTHEAST_ASIA")
  private String SOUTHEAST_ASIA = null;

  @JsonProperty("PK")
  private String PK = null;

  @JsonProperty("MY")
  private String MY = null;

  @JsonProperty("SOUTHERN_ASIA")
  private String SOUTHERN_ASIA = null;

  @JsonProperty("WORLD")
  private String WORLD = null;

  public ResponseRegions ASIA(String ASIA) {
    this.ASIA = ASIA;
    return this;
  }

   /**
   * Get ASIA
   * @return ASIA
  **/
  public String getASIA() {
    return ASIA;
  }

  public void setASIA(String ASIA) {
    this.ASIA = ASIA;
  }

  public ResponseRegions SG(String SG) {
    this.SG = SG;
    return this;
  }

   /**
   * Get SG
   * @return SG
  **/
  public String getSG() {
    return SG;
  }

  public void setSG(String SG) {
    this.SG = SG;
  }

  public ResponseRegions IN(String IN) {
    this.IN = IN;
    return this;
  }

   /**
   * Get IN
   * @return IN
  **/
  public String getIN() {
    return IN;
  }

  public void setIN(String IN) {
    this.IN = IN;
  }

  public ResponseRegions SOUTHEAST_ASIA(String SOUTHEAST_ASIA) {
    this.SOUTHEAST_ASIA = SOUTHEAST_ASIA;
    return this;
  }

   /**
   * Get SOUTHEAST_ASIA
   * @return SOUTHEAST_ASIA
  **/
  public String getSOUTHEASTASIA() {
    return SOUTHEAST_ASIA;
  }

  public void setSOUTHEASTASIA(String SOUTHEAST_ASIA) {
    this.SOUTHEAST_ASIA = SOUTHEAST_ASIA;
  }

  public ResponseRegions PK(String PK) {
    this.PK = PK;
    return this;
  }

   /**
   * Get PK
   * @return PK
  **/
  public String getPK() {
    return PK;
  }

  public void setPK(String PK) {
    this.PK = PK;
  }

  public ResponseRegions MY(String MY) {
    this.MY = MY;
    return this;
  }

   /**
   * Get MY
   * @return MY
  **/
  public String getMY() {
    return MY;
  }

  public void setMY(String MY) {
    this.MY = MY;
  }

  public ResponseRegions SOUTHERN_ASIA(String SOUTHERN_ASIA) {
    this.SOUTHERN_ASIA = SOUTHERN_ASIA;
    return this;
  }

   /**
   * Get SOUTHERN_ASIA
   * @return SOUTHERN_ASIA
  **/
  public String getSOUTHERNASIA() {
    return SOUTHERN_ASIA;
  }

  public void setSOUTHERNASIA(String SOUTHERN_ASIA) {
    this.SOUTHERN_ASIA = SOUTHERN_ASIA;
  }

  public ResponseRegions WORLD(String WORLD) {
    this.WORLD = WORLD;
    return this;
  }

   /**
   * Get WORLD
   * @return WORLD
  **/
  public String getWORLD() {
    return WORLD;
  }

  public void setWORLD(String WORLD) {
    this.WORLD = WORLD;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRegions Response_regions = (ResponseRegions) o;
    return Objects.equals(this.ASIA, Response_regions.ASIA) &&
        Objects.equals(this.SG, Response_regions.SG) &&
        Objects.equals(this.IN, Response_regions.IN) &&
        Objects.equals(this.SOUTHEAST_ASIA, Response_regions.SOUTHEAST_ASIA) &&
        Objects.equals(this.PK, Response_regions.PK) &&
        Objects.equals(this.MY, Response_regions.MY) &&
        Objects.equals(this.SOUTHERN_ASIA, Response_regions.SOUTHERN_ASIA) &&
        Objects.equals(this.WORLD, Response_regions.WORLD);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ASIA, SG, IN, SOUTHEAST_ASIA, PK, MY, SOUTHERN_ASIA, WORLD);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRegions {\n");
    
    sb.append("    ASIA: ").append(toIndentedString(ASIA)).append("\n");
    sb.append("    SG: ").append(toIndentedString(SG)).append("\n");
    sb.append("    IN: ").append(toIndentedString(IN)).append("\n");
    sb.append("    SOUTHEAST_ASIA: ").append(toIndentedString(SOUTHEAST_ASIA)).append("\n");
    sb.append("    PK: ").append(toIndentedString(PK)).append("\n");
    sb.append("    MY: ").append(toIndentedString(MY)).append("\n");
    sb.append("    SOUTHERN_ASIA: ").append(toIndentedString(SOUTHERN_ASIA)).append("\n");
    sb.append("    WORLD: ").append(toIndentedString(WORLD)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
