/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.e_commerce_web_app.opencagedata.model;

import java.util.Objects;
import java.util.Arrays;
import com.e_commerce_web_app.opencagedata.model.ResponseAnnotations;
import com.e_commerce_web_app.opencagedata.model.ResponseBounds;
import com.e_commerce_web_app.opencagedata.model.ResponseComponents;
import com.e_commerce_web_app.opencagedata.model.ResponseGeometry;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseResultsEntryItem
 */

public class ResponseResultsEntryItem {
  @JsonProperty("components")
  private ResponseComponents components = null;

  @JsonProperty("formatted")
  private String formatted = null;

  @JsonProperty("confidence")
  private Integer confidence = null;

  @JsonProperty("bounds")
  private ResponseBounds bounds = null;

  @JsonProperty("annotations")
  private ResponseAnnotations annotations = null;

  @JsonProperty("geometry")
  private ResponseGeometry geometry = null;

  public ResponseResultsEntryItem components(ResponseComponents components) {
    this.components = components;
    return this;
  }

   /**
   * Get components
   * @return components
  **/
  public ResponseComponents getComponents() {
    return components;
  }

  public void setComponents(ResponseComponents components) {
    this.components = components;
  }

  public ResponseResultsEntryItem formatted(String formatted) {
    this.formatted = formatted;
    return this;
  }

   /**
   * Get formatted
   * @return formatted
  **/
  public String getFormatted() {
    return formatted;
  }

  public void setFormatted(String formatted) {
    this.formatted = formatted;
  }

  public ResponseResultsEntryItem confidence(Integer confidence) {
    this.confidence = confidence;
    return this;
  }

   /**
   * Get confidence
   * @return confidence
  **/
  public Integer getConfidence() {
    return confidence;
  }

  public void setConfidence(Integer confidence) {
    this.confidence = confidence;
  }

  public ResponseResultsEntryItem bounds(ResponseBounds bounds) {
    this.bounds = bounds;
    return this;
  }

   /**
   * Get bounds
   * @return bounds
  **/
  public ResponseBounds getBounds() {
    return bounds;
  }

  public void setBounds(ResponseBounds bounds) {
    this.bounds = bounds;
  }

  public ResponseResultsEntryItem annotations(ResponseAnnotations annotations) {
    this.annotations = annotations;
    return this;
  }

   /**
   * Get annotations
   * @return annotations
  **/
  public ResponseAnnotations getAnnotations() {
    return annotations;
  }

  public void setAnnotations(ResponseAnnotations annotations) {
    this.annotations = annotations;
  }

  public ResponseResultsEntryItem geometry(ResponseGeometry geometry) {
    this.geometry = geometry;
    return this;
  }

   /**
   * Get geometry
   * @return geometry
  **/
  public ResponseGeometry getGeometry() {
    return geometry;
  }

  public void setGeometry(ResponseGeometry geometry) {
    this.geometry = geometry;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseResultsEntryItem Response_resultsEntryItem = (ResponseResultsEntryItem) o;
    return Objects.equals(this.components, Response_resultsEntryItem.components) &&
        Objects.equals(this.formatted, Response_resultsEntryItem.formatted) &&
        Objects.equals(this.confidence, Response_resultsEntryItem.confidence) &&
        Objects.equals(this.bounds, Response_resultsEntryItem.bounds) &&
        Objects.equals(this.annotations, Response_resultsEntryItem.annotations) &&
        Objects.equals(this.geometry, Response_resultsEntryItem.geometry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(components, formatted, confidence, bounds, annotations, geometry);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseResultsEntryItem {\n");
    
    sb.append("    components: ").append(toIndentedString(components)).append("\n");
    sb.append("    formatted: ").append(toIndentedString(formatted)).append("\n");
    sb.append("    confidence: ").append(toIndentedString(confidence)).append("\n");
    sb.append("    bounds: ").append(toIndentedString(bounds)).append("\n");
    sb.append("    annotations: ").append(toIndentedString(annotations)).append("\n");
    sb.append("    geometry: ").append(toIndentedString(geometry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
