/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.e_commerce_web_app.opencagedata.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseRise
 */

public class ResponseRise {
  @JsonProperty("astronomical")
  private Integer astronomical = null;

  @JsonProperty("civil")
  private Integer civil = null;

  @JsonProperty("apparent")
  private Integer apparent = null;

  @JsonProperty("nautical")
  private Integer nautical = null;

  public ResponseRise astronomical(Integer astronomical) {
    this.astronomical = astronomical;
    return this;
  }

   /**
   * Get astronomical
   * @return astronomical
  **/
  public Integer getAstronomical() {
    return astronomical;
  }

  public void setAstronomical(Integer astronomical) {
    this.astronomical = astronomical;
  }

  public ResponseRise civil(Integer civil) {
    this.civil = civil;
    return this;
  }

   /**
   * Get civil
   * @return civil
  **/
  public Integer getCivil() {
    return civil;
  }

  public void setCivil(Integer civil) {
    this.civil = civil;
  }

  public ResponseRise apparent(Integer apparent) {
    this.apparent = apparent;
    return this;
  }

   /**
   * Get apparent
   * @return apparent
  **/
  public Integer getApparent() {
    return apparent;
  }

  public void setApparent(Integer apparent) {
    this.apparent = apparent;
  }

  public ResponseRise nautical(Integer nautical) {
    this.nautical = nautical;
    return this;
  }

   /**
   * Get nautical
   * @return nautical
  **/
  public Integer getNautical() {
    return nautical;
  }

  public void setNautical(Integer nautical) {
    this.nautical = nautical;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRise Response_rise = (ResponseRise) o;
    return Objects.equals(this.astronomical, Response_rise.astronomical) &&
        Objects.equals(this.civil, Response_rise.civil) &&
        Objects.equals(this.apparent, Response_rise.apparent) &&
        Objects.equals(this.nautical, Response_rise.nautical);
  }

  @Override
  public int hashCode() {
    return Objects.hash(astronomical, civil, apparent, nautical);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRise {\n");
    
    sb.append("    astronomical: ").append(toIndentedString(astronomical)).append("\n");
    sb.append("    civil: ").append(toIndentedString(civil)).append("\n");
    sb.append("    apparent: ").append(toIndentedString(apparent)).append("\n");
    sb.append("    nautical: ").append(toIndentedString(nautical)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
