/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.e_commerce_web_app.opencagedata.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseStayInformed
 */

public class ResponseStayInformed {
  @JsonProperty("twitter")
  private String twitter = null;

  @JsonProperty("mastodon")
  private String mastodon = null;

  @JsonProperty("blog")
  private String blog = null;

  public ResponseStayInformed twitter(String twitter) {
    this.twitter = twitter;
    return this;
  }

   /**
   * Get twitter
   * @return twitter
  **/
  public String getTwitter() {
    return twitter;
  }

  public void setTwitter(String twitter) {
    this.twitter = twitter;
  }

  public ResponseStayInformed mastodon(String mastodon) {
    this.mastodon = mastodon;
    return this;
  }

   /**
   * Get mastodon
   * @return mastodon
  **/
  public String getMastodon() {
    return mastodon;
  }

  public void setMastodon(String mastodon) {
    this.mastodon = mastodon;
  }

  public ResponseStayInformed blog(String blog) {
    this.blog = blog;
    return this;
  }

   /**
   * Get blog
   * @return blog
  **/
  public String getBlog() {
    return blog;
  }

  public void setBlog(String blog) {
    this.blog = blog;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseStayInformed Response_stay_informed = (ResponseStayInformed) o;
    return Objects.equals(this.twitter, Response_stay_informed.twitter) &&
        Objects.equals(this.mastodon, Response_stay_informed.mastodon) &&
        Objects.equals(this.blog, Response_stay_informed.blog);
  }

  @Override
  public int hashCode() {
    return Objects.hash(twitter, mastodon, blog);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseStayInformed {\n");
    
    sb.append("    twitter: ").append(toIndentedString(twitter)).append("\n");
    sb.append("    mastodon: ").append(toIndentedString(mastodon)).append("\n");
    sb.append("    blog: ").append(toIndentedString(blog)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
