/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.e_commerce_web_app.opencagedata.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseOSM
 */

public class ResponseOSM {
  @JsonProperty("note_url")
  private String note_url = null;

  @JsonProperty("edit_url")
  private String edit_url = null;

  @JsonProperty("url")
  private String url = null;

  public ResponseOSM note_url(String note_url) {
    this.note_url = note_url;
    return this;
  }

   /**
   * Get note_url
   * @return note_url
  **/
  public String getNoteUrl() {
    return note_url;
  }

  public void setNoteUrl(String note_url) {
    this.note_url = note_url;
  }

  public ResponseOSM edit_url(String edit_url) {
    this.edit_url = edit_url;
    return this;
  }

   /**
   * Get edit_url
   * @return edit_url
  **/
  public String getEditUrl() {
    return edit_url;
  }

  public void setEditUrl(String edit_url) {
    this.edit_url = edit_url;
  }

  public ResponseOSM url(String url) {
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseOSM Response_OSM = (ResponseOSM) o;
    return Objects.equals(this.note_url, Response_OSM.note_url) &&
        Objects.equals(this.edit_url, Response_OSM.edit_url) &&
        Objects.equals(this.url, Response_OSM.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(note_url, edit_url, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseOSM {\n");
    
    sb.append("    note_url: ").append(toIndentedString(note_url)).append("\n");
    sb.append("    edit_url: ").append(toIndentedString(edit_url)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
