/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.e_commerce_web_app.opencagedata.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseRoadinfo
 */

public class ResponseRoadinfo {
  @JsonProperty("drive_on")
  private String drive_on = null;

  @JsonProperty("speed_in")
  private String speed_in = null;

  @JsonProperty("road")
  private String road = null;

  public ResponseRoadinfo drive_on(String drive_on) {
    this.drive_on = drive_on;
    return this;
  }

   /**
   * Get drive_on
   * @return drive_on
  **/
  public String getDriveOn() {
    return drive_on;
  }

  public void setDriveOn(String drive_on) {
    this.drive_on = drive_on;
  }

  public ResponseRoadinfo speed_in(String speed_in) {
    this.speed_in = speed_in;
    return this;
  }

   /**
   * Get speed_in
   * @return speed_in
  **/
  public String getSpeedIn() {
    return speed_in;
  }

  public void setSpeedIn(String speed_in) {
    this.speed_in = speed_in;
  }

  public ResponseRoadinfo road(String road) {
    this.road = road;
    return this;
  }

   /**
   * Get road
   * @return road
  **/
  public String getRoad() {
    return road;
  }

  public void setRoad(String road) {
    this.road = road;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRoadinfo Response_roadinfo = (ResponseRoadinfo) o;
    return Objects.equals(this.drive_on, Response_roadinfo.drive_on) &&
        Objects.equals(this.speed_in, Response_roadinfo.speed_in) &&
        Objects.equals(this.road, Response_roadinfo.road);
  }

  @Override
  public int hashCode() {
    return Objects.hash(drive_on, speed_in, road);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRoadinfo {\n");
    
    sb.append("    drive_on: ").append(toIndentedString(drive_on)).append("\n");
    sb.append("    speed_in: ").append(toIndentedString(speed_in)).append("\n");
    sb.append("    road: ").append(toIndentedString(road)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
